Display error details when plpydbapi.Error is raised
This patch will show errors like:

InternalError: plpydbapi.Error: duplicate key value violates unique
constraint "files_pkey"

instead of:

InternalError: plpydbapi.Error: